import { GB } from "./limits";
import type { UsageReport } from "./types";

/** Made-up numbers for the "Try a sample" button. No real account is behind this. */
export const SAMPLE_REPORT: UsageReport = {
  account: { id: "0123456789abcdef0123456789abcdef", name: "Sample account" },
  token: { expiresOn: "2026-10-09T00:00:00Z" },
  fetchedAt: "2026-10-08T14:32:00Z",
  window: { day: "2026-10-08", monthStart: "2026-10-01" },
  products: [
    {
      id: "workers",
      name: "Workers",
      metrics: [
        {
          id: "workers.requests",
          label: "Requests",
          limit: 100_000,
          unit: "count",
          period: "day",
          used: 61_840,
          note: "Pages Functions requests count towards this too.",
        },
      ],
    },
    {
      id: "kv",
      name: "Workers KV",
      metrics: [
        {
          id: "kv.reads",
          label: "Keys read",
          limit: 100_000,
          unit: "count",
          period: "day",
          used: 8_412,
        },
        {
          id: "kv.writes",
          label: "Keys written",
          limit: 1_000,
          unit: "count",
          period: "day",
          used: 940,
        },
        {
          id: "kv.deletes",
          label: "Keys deleted",
          limit: 1_000,
          unit: "count",
          period: "day",
          used: 12,
        },
        {
          id: "kv.lists",
          label: "List requests",
          limit: 1_000,
          unit: "count",
          period: "day",
          used: 3,
        },
        {
          id: "kv.storage",
          label: "Stored data",
          limit: GB,
          unit: "bytes",
          period: "total",
          used: 0.21 * GB,
        },
      ],
    },
    {
      id: "r2",
      name: "R2",
      metrics: [
        {
          id: "r2.classA",
          label: "Class A operations",
          limit: 1_000_000,
          unit: "count",
          period: "month",
          used: 184_300,
          note: "Writes, lists and multipart operations.",
        },
        {
          id: "r2.classB",
          label: "Class B operations",
          limit: 10_000_000,
          unit: "count",
          period: "month",
          used: 2_418_000,
          note: "Reads and head requests.",
        },
        {
          id: "r2.storage",
          label: "Standard storage",
          limit: 10 * GB,
          unit: "bytes",
          period: "total",
          used: 7.4 * GB,
          note: "The free allowance is 10 GB-month of Standard storage.",
        },
      ],
    },
    {
      id: "d1",
      name: "D1",
      metrics: [
        {
          id: "d1.rowsRead",
          label: "Rows read",
          limit: 5_000_000,
          unit: "count",
          period: "day",
          used: 1_230_000,
        },
        {
          id: "d1.rowsWritten",
          label: "Rows written",
          limit: 100_000,
          unit: "count",
          period: "day",
          used: 104_500,
        },
        {
          id: "d1.storage",
          label: "Storage",
          limit: 5 * GB,
          unit: "bytes",
          period: "total",
          used: 0.63 * GB,
        },
      ],
    },
    {
      id: "do",
      name: "Durable Objects",
      metrics: [
        {
          id: "do.requests",
          label: "Requests",
          limit: 100_000,
          unit: "count",
          period: "day",
          used: 4_020,
        },
        {
          id: "do.duration",
          label: "Duration",
          limit: 13_000,
          unit: "gbs",
          period: "day",
          used: 410,
          note: "Wall-clock time while an object is active, at 128 MB per object.",
        },
        {
          id: "do.rowsRead",
          label: "Rows read",
          limit: 5_000_000,
          unit: "count",
          period: "day",
          used: 0,
        },
        {
          id: "do.rowsWritten",
          label: "Rows written",
          limit: 100_000,
          unit: "count",
          period: "day",
          used: 0,
        },
      ],
    },
    {
      id: "queues",
      name: "Queues",
      metrics: [
        {
          id: "queues.operations",
          label: "Operations",
          limit: 10_000,
          unit: "count",
          period: "day",
          used: null,
          error: "This token cannot read the Queues analytics dataset.",
          note: "Writes, reads and deletes together.",
        },
      ],
    },
    {
      id: "ai",
      name: "Workers AI",
      metrics: [
        {
          id: "ai.neurons",
          label: "Neurons",
          limit: 10_000,
          unit: "neurons",
          period: "day",
          used: 2_750,
        },
      ],
    },
  ],
};
